# Schema for the configuration files of the ow_onecall module.
ow_onecall.settings:
  type: config_object
  label: 'Open Weather One Call'
  mapping:
    api_key:
      type: string
      label: 'API key'
    api_key_storage_type:
      type: string
      label: "Storage type"
    environment_storage_key:
      type: string
      label: "Storage key"
    debug:
      type: boolean
      label: "Debug"
